### PR TITLE
Improvements to contributing guide

### PR DESCRIPTION
**Pull request by banesullivan**
Here is a draft of some improvements to the contributing guide for you to run with. Would you please update this to your liking and make sure it has clear instructions for local development and testing?

For https://github.com/pyOpenSci/software-submission/issues/138

### CODE REVIEW

**Comment by raphaelquast** [comment]
Thank you very much for opening this PR! Highly appreciated! I'll report back once it's finished.

**Comment by raphaelquast** [comment]
Hey @banesullivan 
Both `CONTRIBUTING.md` and the associated `Contribution Guide` in the docs are now updated to include infos on tests etc.

- I've decided to only provide a quick-overview in `CONTRIBUTING.md` and link to the docs for more extensive explanations.
- I've switched the base to the `dev` branch so I can already use the `MySt` syntax

Please let me know if you are OK with the changes! 

If yes, I'll merge this PR into dev so it will be included in the next release!

**Review by banesullivan — COMMENTED** [review]
This looks great to me! Thanks for addressing all of this!

**Comment by raphaelquast** [comment]
Thanks for your support and your prompt feedback!

**Pull request merged**
